#!/bin/bash

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
netstat -tuln | awk '{print $1, $4, $5, $6}' | grep LISTEN | while read proto local foreign state; do
    pid=$(lsof -i -n -P | grep -E "LISTEN.*$local.*$proto" | awk '{print $2}')
    program=$(ps -p $pid -o comm=)
    echo "$proto   -   $local   -   $foreign   -   $state   -   $pid/$program"
done

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"
netstat -lx | grep LISTEN | while read proto refcnt flags type state inode; do
    pid=$(lsof -U -n | grep "$inode" | awk '{print $2}')
    program=$(ps -p $pid -o comm=)
    path=$(lsof -U -n | grep "$inode" | awk '{print $9}')
    echo "$proto   -   $refcnt   -   $flags   -   $type   -   $state   -   $inode   -   $pid/$program   -   $path"
done
