#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Display header
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"

# Get all processes and their details
ps -e -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest | awk '{printf "%-10s %5d %4.1f %4.1f %6d %5d %-8s %4s %s %s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11}'
