#!/usr/bin/env bash
# This script is displaying "4-to_infinity_and_beyond process"

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$pid" ]; then
    echo "Process not found"
else
    # Send a termination signal to the process
    kill "$pid"
fi
