#!/usr/bin/env bash
# This script is stopping "4-to_infinity_and_beyond process"

id=$(pgrep -f "4-to_infinity_and_beyond")

if [ -z "$pid" ]; then
    echo "Process not found"
else
    # Send an interrupt signal to the process
    kill -2 "$pid"
fi
