#!/bin/bash

# Use ip command to get IPv4 addresses
ip_addresses=$(ip addr show | grep 'inet ' | awk '{print $2}')

# Filter out loopback addresses (127.0.0.0/8)
for ip in $ip_addresses; do
  if [[ ! $ip =~ ^127\.0\.0\.[0-9]{1,3} ]]; then
    echo "$ip"
  fi
done
